{
 "title": "MariaDB Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MariaDB Server Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_up", "legendFormat": "Server Status(1=UP , 0=Down)" }
   ]
  },
  {
   "title": "Total DB Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"select\"}",
     "legendFormat": "Total DB Reads"
    }
   ]
  },
  {
   "title": "Active DB Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active DB Connections"
    }
   ]
  },
  {
   "title": "Total DB Inserts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"insert\"}",
     "legendFormat": "Total DB Inserts"
    }
   ]
  }
 ]
}