apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  labels:
    k8s-app: backend-monitor
  namespace: operators 
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      tier: monitor-app
  endpoints:
    - interval: 20s
      port: monitor
