apiVersion: mariadb.persistentsys/v1alpha1
kind: Backup
metadata:
  name: mariadb-backup
spec:
  # Backup Path
  backupPath: "/mnt/backup"

  # Backup Size (Ex. 1Gi, 100Mi)
  backupSize: "1Gi" 

  # Schedule period for the CronJob.
  # This spec allow you setup the backup frequency
  # Default: "0 0 * * *" # daily at 00:00
  schedule: "0 0 * * *"

  # Enable Cluster flag
  # Set to true for cluster setup, else false
  clusterEnabled: true


  # If Cluster is enabled, set name of any cluster CR
  clusterCrName: "mariadbcluster-db1"

  

