apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mariadbclusters.mariadb.persistentsys
spec:
  group: mariadb.persistentsys
  names:
    kind: MariaDBCluster
    listKind: MariaDBClusterList
    plural: mariadbclusters
    singular: mariadbcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MariaDBCluster is the Schema for the mariadbclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MariaDBClusterSpec defines the desired state of MariaDBCluster
          properties:
            cluster:
              description: Cluster Configuration
              properties:
                enabled:
                  type: boolean
                firstNode:
                  description: Specifies if this is first node in cluster and will
                    initiate a new cluster
                  type: boolean
                nodeName:
                  description: Name of Node where this pod instance is to be deployed
                  type: string
              required:
              - nodeName
              type: object
            dataStoragePath:
              description: Database storage Path
              type: string
            dataStorageSize:
              description: Database storage Size (Ex. 1Gi, 100Mi)
              type: string
            database:
              description: New Database name
              type: string
            image:
              description: Image name with version
              type: string
            password:
              description: Database additional user password (base64 encoded)
              type: string
            port:
              description: Port number exposed for Database service
              format: int32
              type: integer
            rootpwd:
              description: Root user password
              type: string
            username:
              description: Database additional user details (base64 encoded)
              type: string
          required:
          - dataStoragePath
          - dataStorageSize
          - database
          - image
          - password
          - port
          - rootpwd
          - username
          type: object
        status:
          description: MariaDBClusterStatus defines the observed state of MariaDBCluster
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
